version: "3.7"

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 123456
            PGDATA: /var/lib/postgresql/data/pgdata
        ports: 
            - 5432:5432
        volumes:
            - postgresv:/var/lib/postgresql/data
volumes:
    postgresv: